[package]
name = "pizza-timer-rs"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Reinhard Bronner"]

[dependencies]
chrono = "0.4.35"
iced = { git = "https://github.com/iced-rs/iced.git", features = ["tokio"]}
thiserror = "1.0.40"
tokio = { version = "1.27.0", features = ["full"] }
